//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSUNOEE
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSUNOEE.WSUNOEESoap")]
    public interface WSUNOEESoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearConexionXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSUNOEE.CrearConexionXMLResponse CrearConexionXML(WSUNOEE.CrearConexionXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearConexionXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WSUNOEE.CrearConexionXMLResponse> CrearConexionXMLAsync(WSUNOEE.CrearConexionXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EjecutarConsultaXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSUNOEE.EjecutarConsultaXMLResponse EjecutarConsultaXML(WSUNOEE.EjecutarConsultaXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EjecutarConsultaXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WSUNOEE.EjecutarConsultaXMLResponse> EjecutarConsultaXMLAsync(WSUNOEE.EjecutarConsultaXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeerEsquemaParametros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSUNOEE.LeerEsquemaParametrosResponse LeerEsquemaParametros(WSUNOEE.LeerEsquemaParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeerEsquemaParametros", ReplyAction="*")]
        System.Threading.Tasks.Task<WSUNOEE.LeerEsquemaParametrosResponse> LeerEsquemaParametrosAsync(WSUNOEE.LeerEsquemaParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiesaCFD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSUNOEE.SiesaCFDResponse SiesaCFD(WSUNOEE.SiesaCFDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiesaCFD", ReplyAction="*")]
        System.Threading.Tasks.Task<WSUNOEE.SiesaCFDResponse> SiesaCFDAsync(WSUNOEE.SiesaCFDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportarXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSUNOEE.ImportarXMLResponse ImportarXML(WSUNOEE.ImportarXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportarXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WSUNOEE.ImportarXMLResponse> ImportarXMLAsync(WSUNOEE.ImportarXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InicializarVariablesImportacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSUNOEE.InicializarVariablesImportacionResponse InicializarVariablesImportacion(WSUNOEE.InicializarVariablesImportacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InicializarVariablesImportacion", ReplyAction="*")]
        System.Threading.Tasks.Task<WSUNOEE.InicializarVariablesImportacionResponse> InicializarVariablesImportacionAsync(WSUNOEE.InicializarVariablesImportacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiesaWEBContabilizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSUNOEE.SiesaWEBContabilizarResponse SiesaWEBContabilizar(WSUNOEE.SiesaWEBContabilizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiesaWEBContabilizar", ReplyAction="*")]
        System.Threading.Tasks.Task<WSUNOEE.SiesaWEBContabilizarResponse> SiesaWEBContabilizarAsync(WSUNOEE.SiesaWEBContabilizarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearConexionXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CrearConexionXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pvstrxmlConexion;
        
        public CrearConexionXMLRequest()
        {
        }
        
        public CrearConexionXMLRequest(string pvstrxmlConexion)
        {
            this.pvstrxmlConexion = pvstrxmlConexion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearConexionXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CrearConexionXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CrearConexionXMLResult;
        
        public CrearConexionXMLResponse()
        {
        }
        
        public CrearConexionXMLResponse(bool CrearConexionXMLResult)
        {
            this.CrearConexionXMLResult = CrearConexionXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EjecutarConsultaXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EjecutarConsultaXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pvstrxmlParametros;
        
        public EjecutarConsultaXMLRequest()
        {
        }
        
        public EjecutarConsultaXMLRequest(string pvstrxmlParametros)
        {
            this.pvstrxmlParametros = pvstrxmlParametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EjecutarConsultaXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EjecutarConsultaXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WSUNOEE.ArrayOfXElement EjecutarConsultaXMLResult;
        
        public EjecutarConsultaXMLResponse()
        {
        }
        
        public EjecutarConsultaXMLResponse(WSUNOEE.ArrayOfXElement EjecutarConsultaXMLResult)
        {
            this.EjecutarConsultaXMLResult = EjecutarConsultaXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LeerEsquemaParametros", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LeerEsquemaParametrosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pvstrxmlParametros;
        
        public LeerEsquemaParametrosRequest()
        {
        }
        
        public LeerEsquemaParametrosRequest(string pvstrxmlParametros)
        {
            this.pvstrxmlParametros = pvstrxmlParametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LeerEsquemaParametrosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LeerEsquemaParametrosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LeerEsquemaParametrosResult;
        
        public LeerEsquemaParametrosResponse()
        {
        }
        
        public LeerEsquemaParametrosResponse(string LeerEsquemaParametrosResult)
        {
            this.LeerEsquemaParametrosResult = LeerEsquemaParametrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SiesaCFD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SiesaCFDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short pvintcia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pvstrCo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pvstrTipoDocto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public long pvintConsecInicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public long pvintConsecFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string pvintConexion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public long pvintTimeOut;
        
        public SiesaCFDRequest()
        {
        }
        
        public SiesaCFDRequest(short pvintcia, string pvstrCo, string pvstrTipoDocto, long pvintConsecInicial, long pvintConsecFinal, string pvintConexion, long pvintTimeOut)
        {
            this.pvintcia = pvintcia;
            this.pvstrCo = pvstrCo;
            this.pvstrTipoDocto = pvstrTipoDocto;
            this.pvintConsecInicial = pvintConsecInicial;
            this.pvintConsecFinal = pvintConsecFinal;
            this.pvintConexion = pvintConexion;
            this.pvintTimeOut = pvintTimeOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SiesaCFDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SiesaCFDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object SiesaCFDResult;
        
        public SiesaCFDResponse()
        {
        }
        
        public SiesaCFDResponse(object SiesaCFDResult)
        {
            this.SiesaCFDResult = SiesaCFDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImportarXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pvstrDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short printTipoError;
        
        public ImportarXMLRequest()
        {
        }
        
        public ImportarXMLRequest(string pvstrDatos, short printTipoError)
        {
            this.pvstrDatos = pvstrDatos;
            this.printTipoError = printTipoError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImportarXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WSUNOEE.ArrayOfXElement ImportarXMLResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short printTipoError;
        
        public ImportarXMLResponse()
        {
        }
        
        public ImportarXMLResponse(WSUNOEE.ArrayOfXElement ImportarXMLResult, short printTipoError)
        {
            this.ImportarXMLResult = ImportarXMLResult;
            this.printTipoError = printTipoError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InicializarVariablesImportacion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InicializarVariablesImportacionRequest
    {
        
        public InicializarVariablesImportacionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InicializarVariablesImportacionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InicializarVariablesImportacionResponse
    {
        
        public InicializarVariablesImportacionResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SiesaWEBContabilizar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SiesaWEBContabilizarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pvstrParametros;
        
        public SiesaWEBContabilizarRequest()
        {
        }
        
        public SiesaWEBContabilizarRequest(string pvstrParametros)
        {
            this.pvstrParametros = pvstrParametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SiesaWEBContabilizarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SiesaWEBContabilizarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short SiesaWEBContabilizarResult;
        
        public SiesaWEBContabilizarResponse()
        {
        }
        
        public SiesaWEBContabilizarResponse(short SiesaWEBContabilizarResult)
        {
            this.SiesaWEBContabilizarResult = SiesaWEBContabilizarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WSUNOEESoapChannel : WSUNOEE.WSUNOEESoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WSUNOEESoapClient : System.ServiceModel.ClientBase<WSUNOEE.WSUNOEESoap>, WSUNOEE.WSUNOEESoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSUNOEESoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSUNOEESoapClient.GetBindingForEndpoint(endpointConfiguration), WSUNOEESoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSUNOEESoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSUNOEESoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSUNOEESoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSUNOEESoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSUNOEESoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WSUNOEE.CrearConexionXMLResponse CrearConexionXML(WSUNOEE.CrearConexionXMLRequest request)
        {
            return base.Channel.CrearConexionXML(request);
        }
        
        public System.Threading.Tasks.Task<WSUNOEE.CrearConexionXMLResponse> CrearConexionXMLAsync(WSUNOEE.CrearConexionXMLRequest request)
        {
            return base.Channel.CrearConexionXMLAsync(request);
        }
        
        public WSUNOEE.EjecutarConsultaXMLResponse EjecutarConsultaXML(WSUNOEE.EjecutarConsultaXMLRequest request)
        {
            return base.Channel.EjecutarConsultaXML(request);
        }
        
        public System.Threading.Tasks.Task<WSUNOEE.EjecutarConsultaXMLResponse> EjecutarConsultaXMLAsync(WSUNOEE.EjecutarConsultaXMLRequest request)
        {
            return base.Channel.EjecutarConsultaXMLAsync(request);
        }
        
        public WSUNOEE.LeerEsquemaParametrosResponse LeerEsquemaParametros(WSUNOEE.LeerEsquemaParametrosRequest request)
        {
            return base.Channel.LeerEsquemaParametros(request);
        }
        
        public System.Threading.Tasks.Task<WSUNOEE.LeerEsquemaParametrosResponse> LeerEsquemaParametrosAsync(WSUNOEE.LeerEsquemaParametrosRequest request)
        {
            return base.Channel.LeerEsquemaParametrosAsync(request);
        }
        
        public WSUNOEE.SiesaCFDResponse SiesaCFD(WSUNOEE.SiesaCFDRequest request)
        {
            return base.Channel.SiesaCFD(request);
        }
        
        public System.Threading.Tasks.Task<WSUNOEE.SiesaCFDResponse> SiesaCFDAsync(WSUNOEE.SiesaCFDRequest request)
        {
            return base.Channel.SiesaCFDAsync(request);
        }
        
        public WSUNOEE.ImportarXMLResponse ImportarXML(WSUNOEE.ImportarXMLRequest request)
        {
            return base.Channel.ImportarXML(request);
        }
        
        public System.Threading.Tasks.Task<WSUNOEE.ImportarXMLResponse> ImportarXMLAsync(WSUNOEE.ImportarXMLRequest request)
        {
            return base.Channel.ImportarXMLAsync(request);
        }
        
        public WSUNOEE.InicializarVariablesImportacionResponse InicializarVariablesImportacion(WSUNOEE.InicializarVariablesImportacionRequest request)
        {
            return base.Channel.InicializarVariablesImportacion(request);
        }
        
        public System.Threading.Tasks.Task<WSUNOEE.InicializarVariablesImportacionResponse> InicializarVariablesImportacionAsync(WSUNOEE.InicializarVariablesImportacionRequest request)
        {
            return base.Channel.InicializarVariablesImportacionAsync(request);
        }
        
        public WSUNOEE.SiesaWEBContabilizarResponse SiesaWEBContabilizar(WSUNOEE.SiesaWEBContabilizarRequest request)
        {
            return base.Channel.SiesaWEBContabilizar(request);
        }
        
        public System.Threading.Tasks.Task<WSUNOEE.SiesaWEBContabilizarResponse> SiesaWEBContabilizarAsync(WSUNOEE.SiesaWEBContabilizarRequest request)
        {
            return base.Channel.SiesaWEBContabilizarAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSUNOEESoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSUNOEESoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSUNOEESoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.105:8081/WMS_WSUNOEE_ODISEO/WSUNOEE.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSUNOEESoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.105:8081/WMS_WSUNOEE_ODISEO/WSUNOEE.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSUNOEESoap,
            
            WSUNOEESoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
