//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;

namespace WSGT
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://generictransfer.com/", ConfigurationName="WSGT.wsGenerarPlanoSoap")]
    public interface wsGenerarPlanoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/GenerarPlanoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSGT.GenerarPlanoXMLResponse GenerarPlanoXML(WSGT.GenerarPlanoXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/GenerarPlanoXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WSGT.GenerarPlanoXMLResponse> GenerarPlanoXMLAsync(WSGT.GenerarPlanoXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/ImportarDatosXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSGT.ImportarDatosXMLResponse ImportarDatosXML(WSGT.ImportarDatosXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/ImportarDatosXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WSGT.ImportarDatosXMLResponse> ImportarDatosXMLAsync(WSGT.ImportarDatosXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/ImportarDatosDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSGT.ImportarDatosDSResponse ImportarDatosDS(WSGT.ImportarDatosDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/ImportarDatosDS", ReplyAction="*")]
        System.Threading.Tasks.Task<WSGT.ImportarDatosDSResponse> ImportarDatosDSAsync(WSGT.ImportarDatosDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/ImportarDatosTablasXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSGT.ImportarDatosTablasXMLResponse ImportarDatosTablasXML(WSGT.ImportarDatosTablasXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/ImportarDatosTablasXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WSGT.ImportarDatosTablasXMLResponse> ImportarDatosTablasXMLAsync(WSGT.ImportarDatosTablasXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/ImportarDatosTablasDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSGT.ImportarDatosTablasDSResponse ImportarDatosTablasDS(WSGT.ImportarDatosTablasDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://generictransfer.com/ImportarDatosTablasDS", ReplyAction="*")]
        System.Threading.Tasks.Task<WSGT.ImportarDatosTablasDSResponse> ImportarDatosTablasDSAsync(WSGT.ImportarDatosTablasDSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarPlanoXML", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class GenerarPlanoXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public int idDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string strNombreDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=2)]
        public int idCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=3)]
        public string strCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=4)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=5)]
        public string strClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=6)]
        public DataSet dsFuenteDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=7)]
        public string Path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=8)]
        public string strResultado;
        
        public GenerarPlanoXMLRequest()
        {
        }
        
        public GenerarPlanoXMLRequest(int idDocumento, string strNombreDocumento, int idCompania, string strCompania, string strUsuario, string strClave, DataSet dsFuenteDatos, string Path, string strResultado)
        {
            this.idDocumento = idDocumento;
            this.strNombreDocumento = strNombreDocumento;
            this.idCompania = idCompania;
            this.strCompania = strCompania;
            this.strUsuario = strUsuario;
            this.strClave = strClave;
            this.dsFuenteDatos = dsFuenteDatos;
            this.Path = Path;
            this.strResultado = strResultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarPlanoXMLResponse", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class GenerarPlanoXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public string GenerarPlanoXMLResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string Path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=2)]
        public string strResultado;
        
        public GenerarPlanoXMLResponse()
        {
        }
        
        public GenerarPlanoXMLResponse(string GenerarPlanoXMLResult, string Path, string strResultado)
        {
            this.GenerarPlanoXMLResult = GenerarPlanoXMLResult;
            this.Path = Path;
            this.strResultado = strResultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarDatosXML", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class ImportarDatosXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public int idDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string strNombreDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=2)]
        public int idCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=3)]
        public string strCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=4)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=5)]
        public string strClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=6)]
        public string strFuenteDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=7)]
        public string Path;
        
        public ImportarDatosXMLRequest()
        {
        }
        
        public ImportarDatosXMLRequest(int idDocumento, string strNombreDocumento, int idCompania, string strCompania, string strUsuario, string strClave, string strFuenteDatos, string Path)
        {
            this.idDocumento = idDocumento;
            this.strNombreDocumento = strNombreDocumento;
            this.idCompania = idCompania;
            this.strCompania = strCompania;
            this.strUsuario = strUsuario;
            this.strClave = strClave;
            this.strFuenteDatos = strFuenteDatos;
            this.Path = Path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarDatosXMLResponse", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class ImportarDatosXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public string ImportarDatosXMLResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string Path;
        
        public ImportarDatosXMLResponse()
        {
        }
        
        public ImportarDatosXMLResponse(string ImportarDatosXMLResult, string Path)
        {
            this.ImportarDatosXMLResult = ImportarDatosXMLResult;
            this.Path = Path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarDatosDS", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class ImportarDatosDSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public int idDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string strNombreDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=2)]
        public int idCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=3)]
        public string strCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=4)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=5)]
        public string strClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=6)]
        public DataSet dsFuenteDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=7)]
        public string Path;
        
        public ImportarDatosDSRequest()
        {
        }
        
        public ImportarDatosDSRequest(int idDocumento, string strNombreDocumento, int idCompania, string strCompania, string strUsuario, string strClave, DataSet dsFuenteDatos, string Path)
        {
            this.idDocumento = idDocumento;
            this.strNombreDocumento = strNombreDocumento;
            this.idCompania = idCompania;
            this.strCompania = strCompania;
            this.strUsuario = strUsuario;
            this.strClave = strClave;
            this.dsFuenteDatos = dsFuenteDatos;
            this.Path = Path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarDatosDSResponse", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class ImportarDatosDSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public string ImportarDatosDSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string Path;
        
        public ImportarDatosDSResponse()
        {
        }
        
        public ImportarDatosDSResponse(string ImportarDatosDSResult, string Path)
        {
            this.ImportarDatosDSResult = ImportarDatosDSResult;
            this.Path = Path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarDatosTablasXML", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class ImportarDatosTablasXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public int idDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string strNombreDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=2)]
        public int idCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=3)]
        public string strCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=4)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=5)]
        public string strClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=6)]
        public string strFuenteDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=7)]
        public string tsProceso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=8)]
        public string Path;
        
        public ImportarDatosTablasXMLRequest()
        {
        }
        
        public ImportarDatosTablasXMLRequest(int idDocumento, string strNombreDocumento, int idCompania, string strCompania, string strUsuario, string strClave, string strFuenteDatos, string tsProceso, string Path)
        {
            this.idDocumento = idDocumento;
            this.strNombreDocumento = strNombreDocumento;
            this.idCompania = idCompania;
            this.strCompania = strCompania;
            this.strUsuario = strUsuario;
            this.strClave = strClave;
            this.strFuenteDatos = strFuenteDatos;
            this.tsProceso = tsProceso;
            this.Path = Path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarDatosTablasXMLResponse", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class ImportarDatosTablasXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public string ImportarDatosTablasXMLResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string Path;
        
        public ImportarDatosTablasXMLResponse()
        {
        }
        
        public ImportarDatosTablasXMLResponse(string ImportarDatosTablasXMLResult, string Path)
        {
            this.ImportarDatosTablasXMLResult = ImportarDatosTablasXMLResult;
            this.Path = Path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarDatosTablasDS", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class ImportarDatosTablasDSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public int idDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string strNombreDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=2)]
        public int idCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=3)]
        public string strCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=4)]
        public string strUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=5)]
        public string strClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=6)]
        public WSGT.ArrayOfXElement dsFuenteDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=7)]
        public string tsProceso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=8)]
        public string Path;
        
        public ImportarDatosTablasDSRequest()
        {
        }
        
        public ImportarDatosTablasDSRequest(int idDocumento, string strNombreDocumento, int idCompania, string strCompania, string strUsuario, string strClave, WSGT.ArrayOfXElement dsFuenteDatos, string tsProceso, string Path)
        {
            this.idDocumento = idDocumento;
            this.strNombreDocumento = strNombreDocumento;
            this.idCompania = idCompania;
            this.strCompania = strCompania;
            this.strUsuario = strUsuario;
            this.strClave = strClave;
            this.dsFuenteDatos = dsFuenteDatos;
            this.tsProceso = tsProceso;
            this.Path = Path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportarDatosTablasDSResponse", WrapperNamespace="http://generictransfer.com/", IsWrapped=true)]
    public partial class ImportarDatosTablasDSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=0)]
        public string ImportarDatosTablasDSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generictransfer.com/", Order=1)]
        public string Path;
        
        public ImportarDatosTablasDSResponse()
        {
        }
        
        public ImportarDatosTablasDSResponse(string ImportarDatosTablasDSResult, string Path)
        {
            this.ImportarDatosTablasDSResult = ImportarDatosTablasDSResult;
            this.Path = Path;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface wsGenerarPlanoSoapChannel : WSGT.wsGenerarPlanoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class wsGenerarPlanoSoapClient : System.ServiceModel.ClientBase<WSGT.wsGenerarPlanoSoap>, WSGT.wsGenerarPlanoSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsGenerarPlanoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsGenerarPlanoSoapClient.GetBindingForEndpoint(endpointConfiguration), wsGenerarPlanoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsGenerarPlanoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsGenerarPlanoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsGenerarPlanoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsGenerarPlanoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsGenerarPlanoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WSGT.GenerarPlanoXMLResponse GenerarPlanoXML(WSGT.GenerarPlanoXMLRequest request)
        {
            return base.Channel.GenerarPlanoXML(request);
        }
        
        public System.Threading.Tasks.Task<WSGT.GenerarPlanoXMLResponse> GenerarPlanoXMLAsync(WSGT.GenerarPlanoXMLRequest request)
        {
            return base.Channel.GenerarPlanoXMLAsync(request);
        }
        
        public WSGT.ImportarDatosXMLResponse ImportarDatosXML(WSGT.ImportarDatosXMLRequest request)
        {
            return base.Channel.ImportarDatosXML(request);
        }
        
        public System.Threading.Tasks.Task<WSGT.ImportarDatosXMLResponse> ImportarDatosXMLAsync(WSGT.ImportarDatosXMLRequest request)
        {
            return base.Channel.ImportarDatosXMLAsync(request);
        }
        
        public WSGT.ImportarDatosDSResponse ImportarDatosDS(WSGT.ImportarDatosDSRequest request)
        {
            return base.Channel.ImportarDatosDS(request);
        }
        
        public System.Threading.Tasks.Task<WSGT.ImportarDatosDSResponse> ImportarDatosDSAsync(WSGT.ImportarDatosDSRequest request)
        {
            return base.Channel.ImportarDatosDSAsync(request);
        }
        
        public WSGT.ImportarDatosTablasXMLResponse ImportarDatosTablasXML(WSGT.ImportarDatosTablasXMLRequest request)
        {
            return base.Channel.ImportarDatosTablasXML(request);
        }
        
        public System.Threading.Tasks.Task<WSGT.ImportarDatosTablasXMLResponse> ImportarDatosTablasXMLAsync(WSGT.ImportarDatosTablasXMLRequest request)
        {
            return base.Channel.ImportarDatosTablasXMLAsync(request);
        }
        
        public WSGT.ImportarDatosTablasDSResponse ImportarDatosTablasDS(WSGT.ImportarDatosTablasDSRequest request)
        {
            return base.Channel.ImportarDatosTablasDS(request);
        }
        
        public System.Threading.Tasks.Task<WSGT.ImportarDatosTablasDSResponse> ImportarDatosTablasDSAsync(WSGT.ImportarDatosTablasDSRequest request)
        {
            return base.Channel.ImportarDatosTablasDSAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsGenerarPlanoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsGenerarPlanoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsGenerarPlanoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.54:8082/ServiciosWeb/wsGenerarPlano.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsGenerarPlanoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.54:8082/ServiciosWeb/wsGenerarPlano.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsGenerarPlanoSoap,
            
            wsGenerarPlanoSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
